platform: linux

image_resource:
  type: docker-image
  source: 
    repository: "nexus-nonprod.cardinalhealth.net:8445/anapsix/alpine-java"
    tag: 8_jdk 

inputs:
  - name: project-source
  - name: nexus-security-tools
  - name: temp-storage
  # - name: build-out
  #
outputs:
  - name: scan-results
run:
  path: "project-source/ci/tasks/check-dependencies.sh"

params:
  TERM: -dumb
