platform: linux

image_resource:
  type: docker-image
  source: 
    repository: "nexus-nonprod.cardinalhealth.net:8445/anapsix/alpine-java"
    tag: latest

inputs:
  - name: nexus-snapshot

outputs:
  - name: result-output
run:
  path: "project-source/ci/tasks/deploy-release.sh"

params:
  TERM: -dump
