platform: linux

image_resource:
  type: docker-image
  source:
    repository: "nexus-nonprod.cardinalhealth.net:8445/anapsix/alpine-java"
inputs:
  - name: project-source
  - name: temp-storage
  - name: build-version
outputs:
  - name: deploy-output

run:
  path: "project-source/ci/tasks/publish-snapshot.sh"
params:
  TERM: -dumb