resources:
  - name: snapshot
    type: s3
    source:
     bucket: releases-cv
     regexp: snapshot/build-(.*).tar
     access_key_id: ((S3_ACCESS_KEY))
     secret_access_key: ((S3_SECRET))
jobs:
- name: job-hello-world
  plan:
  - get: snapshot
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: "nexus-nonprod.cardinalhealth.net:8445/byrnedo/alpine-curl"
        # source: {repository:  "nexus-nonprod.cardinalhealth.net:8445/appropriate/curl"}
      inputs:
        - name: snapshot
      run:
        path: curl
        args: [--help]


