platform: linux

image_resource:
  type: docker-image
  source: 
    repository: "nexus-nonprod.cardinalhealth.net:8445/alvrme/alpine-android"
    tag: latest

inputs:
  - name: project-source
  
caches:
  - path: gradle
  - path: maven

outputs:
  - name: result-out
run:
  path: "project-source/ci/tasks/unit-test.sh"

params:
  TERM: -dump
