platform: linux

image_resource:
  type: docker-image
  source:
    repository: "nexus-nonprod.cardinalhealth.net:8445/anapsix/alpine-java"
    tag: latest

inputs:
  - name: project-source
  - name: build-version

caches:
  - path: gradle
  - path: maven

outputs:
  - name: sonarqube-analysis-input
  - name: build-out
run:
  path: "project-source/ci/tasks/veracode.sh"

params:
  TERM: -dump
